# Generated by Django 6.1.1 on 2026-09-20 04:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0007_movimientoinventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('numero', models.SmallIntegerField(unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada')], default='DISPONIBLE', max_length=10)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('numero__gte', 1), ('numero__lte', 15)), name='mesa_numero_entre_1_y_15')],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('tipo', models.CharField(choices=[('RAPIDA', 'Rapida'), ('SESION_DINAMICA', 'Sesion Dinamica')], max_length=20)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='ABIERTA', max_length=10)),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('medio_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('QR', 'Qr')], max_length=20, null=True)),
                ('estado_pago', models.CharField(blank=True, choices=[('CONFIRMADO', 'Confirmado'), ('PENDIENTE_VERIFICACION', 'Pendiente Verificacion')], max_length=30, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='ventas.mesa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventario.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='ventas.venta')),
            ],
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mesa__isnull', False), ('tipo', 'SESION_DINAMICA')), models.Q(('mesa__isnull', True), ('tipo', 'RAPIDA')), _connector='OR'), name='venta_mesa_segun_tipo'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTA')), fields=('mesa',), name='venta_una_sesion_abierta_por_mesa'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'CERRADA'), _negated=True), models.Q(('fecha_cierre__isnull', False), models.Q(('medio_pago', ''), _negated=True), ('medio_pago__isnull', False), ('estado_pago__isnull', False)), _connector='OR'), name='venta_cerrada_exige_cierre_medio_y_estado_pago'),
        ),
        migrations.AddConstraint(
            model_name='detalleventa',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='detalleventa_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='detalleventa',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='detalleventa_precio_unitario_no_negativo'),
        ),
    ]
