"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Raíz del repositorio (un nivel arriba de backend/), donde vive .env.
ROOT_DIR = BASE_DIR.parent

load_dotenv(ROOT_DIR / '.env')

# Bloque 6a (D25): build de la PWA (frontend/dist) que sirve WhiteNoise/spa_view
# en producción. En desarrollo, si no se ha corrido `npm run build`, no existe;
# spa_view responde 501 en ese caso en vez de fallar al importar settings.
FRONTEND_DIST = ROOT_DIR / 'frontend' / 'dist'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
# B1 (F-13): en producción (DEBUG=False) SECRET_KEY es obligatoria; si falta,
# Django no arranca, en vez de firmar los JWT con la clave de desarrollo.
# Con DEBUG=True (desarrollo, pruebas y el collectstatic del Dockerfile) se
# mantiene el valor de desarrollo.
SECRET_KEY = os.environ.get('SECRET_KEY', '')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            'SECRET_KEY no está definida. En producción (DEBUG=False) es obligatorio '
            'configurarla como variable de entorno.'
        )
    SECRET_KEY = 'django-insecure-g_fxytr76m0$mj^x#hpnvajoz*-7aps9=b7a)r+jve&a=qtwt1'

# Bloque 6a (D25): en producción (Render) llega por env, separado por comas
# (p. ej. "sadim.onrender.com"). En desarrollo, sin la variable, basta localhost.
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Necesario porque Django exige que el origen del formulario/CSRF esté en la
# lista cuando se sirve por HTTPS detrás de un proxy (Render). Vacío en
# desarrollo (no hace falta con runserver en HTTP).
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'core',
    'usuarios',
    'inventario',
    'ventas',
    'servicios',
    'finanzas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Bloque 6a (D25): sirve el build de la PWA y los estáticos del admin
    # directamente desde el proceso de gunicorn, sin un servidor aparte.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Bloque 6a (D25): en producción (Render) llega DATABASE_URL apuntando a Neon,
# que exige SSL. En desarrollo no se define esa variable, así que se sigue
# usando el esquema de variables sueltas de siempre (.env actual, sin cambios).
_DATABASE_URL = os.environ.get('DATABASE_URL')
if _DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(_DATABASE_URL, conn_max_age=600, ssl_require=True),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'sadim_db'),
            'USER': os.environ.get('DB_USER', 'sadim'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-co'

# D10: los resúmenes diarios y el cierre de caja dependen del día local, y el
# Contrato API devuelve fechas con offset -05:00 (ejemplos de las secciones
# 3, 4, 6 y 10). USE_TZ sigue en True: se guarda en UTC y se convierte al
# serializar/mostrar.
TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
# `collectstatic` reúne aquí los estáticos del admin (WhiteNoise los sirve
# desde este directorio bajo /static/, matching gitignore /backend/staticfiles/).
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

# Bloque 6a (D25): sirve el build de la PWA (frontend/dist) desde la raíz del
# dominio (/, /assets/..., /manifest.webmanifest, /sw.js), sin pasar por
# collectstatic ni por STATIC_URL. Solo si el build existe (en desarrollo,
# sin `npm run build`, WhiteNoise simplemente no tiene nada que servir ahí).
if FRONTEND_DIST.is_dir():
    WHITENOISE_ROOT = FRONTEND_DIST

# Los archivos hasheados por Vite viven bajo dist/assets/ (p. ej.
# assets/index-4f2a9c1b.js): son inmutables y pueden cachearse un año.
# Todo lo demás en la raíz del build (index.html, manifest.webmanifest,
# sw.js, registerSW.js, favicon.svg) NO lleva hash en el nombre y debe
# revalidarse siempre, para que las actualizaciones de la PWA lleguen a los
# usuarios sin quedar atrapadas en caché del navegador/CDN.
WHITENOISE_IMMUTABLE_FILE_TEST = lambda path, url: '/assets/' in url
WHITENOISE_MAX_AGE = 0


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Contrato API §14 / IMP-07: toda respuesta de error es {code, message, details}.
    'EXCEPTION_HANDLER': 'core.exceptions.manejador_de_excepciones',
    # Contrato API §2: los valores monetarios y las cantidades salen como
    # número JSON (3500.00), no como texto ("3500.00"). El backend sigue
    # calculando con Decimal; esto solo cambia cómo se serializa hacia afuera.
    'COERCE_DECIMAL_TO_STRING': False,
}
# D23 (Bloque 5b): el refresh vive 7 días para que una sesión guardada en el
# dispositivo siga sirviendo varios días sin conexión (ERD §8.1); el access
# vive poco (30 min) porque el cliente lo renueva solo con /api/auth/refresh/.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}
AUTH_USER_MODEL = 'usuarios.Usuario'

# Al ejecutar `manage.py test`, cambia a un hasher de contraseñas rápido
# (MD5, inseguro) en vez del PBKDF2 por defecto: cada login de cada prueba
# hashea/verifica una contraseña, y con PBKDF2 (~600 000 iteraciones) eso
# domina el tiempo total de la suite. No afecta `runserver` ni producción:
# solo se activa cuando 'test' aparece en el comando invocado.
if 'test' in sys.argv:
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']

# Bloque 6a (D25): Render pone la app detrás de un proxy TLS (el proceso de
# gunicorn recibe HTTP plano), y solo cuando DEBUG=False para no romper
# `runserver`/`manage.py test` en desarrollo.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True