# Generated by Django 6.1.1 on 2026-09-20 04:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('tipo', models.CharField(choices=[('INGRESO_VENTA', 'Ingreso Venta'), ('INGRESO_ABONO', 'Ingreso Abono'), ('GASTO', 'Gasto')], max_length=20)),
                ('medio_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('QR', 'Qr')], max_length=20)),
                ('estado_pago', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('PENDIENTE_VERIFICACION', 'Pendiente Verificacion')], default='CONFIRMADO', max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
