# Generated by Django 6.1.1 on 2026-09-20 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_caja', to='ventas.venta'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='movcaja_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'INGRESO_VENTA'), _negated=True), ('venta__isnull', False), _connector='OR'), name='movcaja_venta_requerida_en_ingreso_venta'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.CheckConstraint(condition=models.Q(('tipo', 'INGRESO_VENTA'), ('venta__isnull', True), _connector='OR'), name='movcaja_venta_nula_fuera_de_ingreso_venta'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'GASTO'), _negated=True), ('concepto__isnull', False), _connector='OR'), name='movcaja_concepto_requerido_en_gasto'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado_pago', 'CONFIRMADO'), ('fecha_confirmacion__isnull', True), _negated=True), ('medio_pago', 'EFECTIVO'), _connector='OR'), name='movcaja_confirmado_sin_fecha_solo_efectivo'),
        ),
    ]
