# Generated by Django 6.1.1 on 2026-09-20 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_initial'),
        ('servicios', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='abono',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_caja', to='servicios.abono'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'INGRESO_ABONO'), _negated=True), ('abono__isnull', False), _connector='OR'), name='movcaja_abono_requerido_en_ingreso_abono'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.CheckConstraint(condition=models.Q(('tipo', 'INGRESO_ABONO'), ('abono__isnull', True), _connector='OR'), name='movcaja_abono_nulo_fuera_de_ingreso_abono'),
        ),
    ]
