# Generated by Django 6.1.1 on 2026-09-21 15:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_movimientocaja_abono_and_more'),
        ('servicios', '0002_alter_abono_estado_pago'),
        ('ventas', '0002_alter_venta_estado_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='motivo_anulacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='estado_pago',
            field=models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('PENDIENTE_VERIFICACION', 'Pendiente Verificacion'), ('ANULADO', 'Anulado')], default='CONFIRMADO', max_length=30),
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('fecha', models.DateField(unique=True)),
                ('periodo_inicio', models.DateTimeField()),
                ('periodo_fin', models.DateTimeField()),
                ('total_ingresos_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ingresos_abonos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('efectivo_esperado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('efectivo_contado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_caja', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='cierre_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finanzas.cierrecaja'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado_pago', 'PENDIENTE_VERIFICACION'), _negated=True), ('cierre_caja__isnull', True), _connector='OR'), name='movcaja_sin_cierre_si_pendiente'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado_pago', 'ANULADO'), _negated=True), ('motivo_anulacion__isnull', False), _connector='OR'), name='movcaja_motivo_anulacion_si_anulado'),
        ),
        migrations.AddConstraint(
            model_name='cierrecaja',
            constraint=models.CheckConstraint(condition=models.Q(('efectivo_contado__gte', 0)), name='cierrecaja_efectivo_contado_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cierrecaja',
            constraint=models.CheckConstraint(condition=models.Q(('periodo_fin__gt', models.F('periodo_inicio'))), name='cierrecaja_periodo_fin_mayor'),
        ),
        migrations.AddConstraint(
            model_name='cierrecaja',
            constraint=models.CheckConstraint(condition=models.Q(('diferencia', 0), ('observaciones__isnull', False), _connector='OR'), name='cierrecaja_observaciones_si_diferencia'),
        ),
    ]
