# Generated by Django 6.1.1 on 2026-10-06 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_movimientocaja_motivo_anulacion_and_more'),
        ('inventario', '0009_movimientoinventario_consumo_orden_and_more'),
        ('servicios', '0003_ordentrabajo_cancelada_por_and_more'),
        ('ventas', '0002_alter_venta_estado_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='movimiento_inventario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gasto_compra', to='inventario.movimientoinventario'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.CheckConstraint(condition=models.Q(('tipo', 'GASTO'), ('movimiento_inventario__isnull', True), _connector='OR'), name='movcaja_movinv_solo_en_gasto'),
        ),
    ]
