# Generated by Django 6.1.1 on 2026-09-20 04:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_producto_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA_VENTA', 'Salida Venta'), ('SALIDA_SERVICIO', 'Salida Servicio'), ('MERMA', 'Merma'), ('AJUSTE_MANUAL', 'Ajuste Manual')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sentido', models.CharField(blank=True, choices=[('SUMA', 'Suma'), ('RESTA', 'Resta')], max_length=10, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
