# Generated by Django 6.1.1 on 2026-09-20 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_movimientoinventario'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='ventas.venta'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['producto', 'fecha'], name='inventario__product_fadacf_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='movinv_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo__in', ['MERMA', 'AJUSTE_MANUAL']), _negated=True), ('motivo__isnull', False), _connector='OR'), name='movinv_motivo_si_merma_o_ajuste'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'AJUSTE_MANUAL'), _negated=True), ('sentido__isnull', False), _connector='OR'), name='movinv_sentido_requerido_en_ajuste'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('tipo', 'AJUSTE_MANUAL'), ('sentido__isnull', True), _connector='OR'), name='movinv_sentido_nulo_fuera_de_ajuste'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'SALIDA_VENTA'), _negated=True), ('venta__isnull', False), _connector='OR'), name='movinv_venta_requerida_en_salida_venta'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('tipo', 'SALIDA_VENTA'), ('venta__isnull', True), _connector='OR'), name='movinv_venta_nula_fuera_de_salida_venta'),
        ),
    ]
