# Generated by Django 6.1.1 on 2026-09-20 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_movimientoinventario_venta_and_more'),
        ('servicios', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='consumo_orden',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_inventario', to='servicios.consumoorden'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'SALIDA_SERVICIO'), _negated=True), ('consumo_orden__isnull', False), _connector='OR'), name='movinv_consumo_requerido_en_salida_servicio'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('tipo', 'SALIDA_SERVICIO'), ('consumo_orden__isnull', True), _connector='OR'), name='movinv_consumo_nulo_fuera_de_salida_servicio'),
        ),
    ]
