# Generated by Django 6.1.1 on 2026-09-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_rol_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(db_column='password_hash', max_length=255),
        ),
    ]
