# Generated by Django 6.1.1 on 2026-09-20 03:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionModulo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ventas_activo', models.BooleanField(default=True)),
                ('inventario_activo', models.BooleanField(default=True)),
                ('servicios_activo', models.BooleanField(default=True)),
                ('finanzas_activo', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identificador', models.UUIDField(unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('es_caja', models.BooleanField(default=False)),
                ('autorizado_offline', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_sincronizacion', models.DateTimeField(blank=True, null=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperacionSincronizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField(unique=True)),
                ('recurso', models.CharField(max_length=60)),
                ('accion', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('estado', models.CharField(choices=[('APLICADA', 'Aplicada'), ('DUPLICADA', 'Duplicada'), ('RECHAZADA', 'Rechazada'), ('CONFLICTO', 'Conflicto')], max_length=10)),
                ('origen', models.CharField(choices=[('EN_LINEA', 'En Linea'), ('SINCRONIZACION', 'Sincronizacion')], max_length=20)),
                ('codigo_conflicto', models.CharField(blank=True, max_length=50, null=True)),
                ('mensaje', models.CharField(blank=True, max_length=255, null=True)),
                ('objeto_id', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('status_code_original', models.PositiveSmallIntegerField()),
                ('fecha_cliente', models.DateTimeField()),
                ('fecha_procesamiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('atendida', models.BooleanField(default=False)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_sincronizacion', to='core.dispositivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_sincronizacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionPago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acepta_efectivo', models.BooleanField(default=True)),
                ('acepta_transferencia', models.BooleanField(default=False)),
                ('acepta_qr', models.BooleanField(default=False)),
                ('nequi_titular', models.CharField(blank=True, max_length=150, null=True)),
                ('nequi_llave', models.CharField(blank=True, max_length=50, null=True)),
                ('actualizado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('acepta_qr', False), ('acepta_transferencia', False)), ('nequi_llave__isnull', False), _connector='OR'), name='configuracionpago_nequi_llave_si_electronico')],
            },
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.UniqueConstraint(condition=models.Q(('autorizado_offline', True)), fields=('autorizado_offline',), name='dispositivo_unico_autorizado_offline'),
        ),
        migrations.AddIndex(
            model_name='operacionsincronizacion',
            index=models.Index(fields=['estado', 'atendida'], name='core_operac_estado_c033eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='operacionsincronizacion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado__in', ['RECHAZADA', 'CONFLICTO']), _negated=True), ('codigo_conflicto__isnull', False), _connector='OR'), name='operacionsync_codigo_conflicto_si_rechazo'),
        ),
        migrations.AddConstraint(
            model_name='operacionsincronizacion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'APLICADA'), _negated=True), ('objeto_id__isnull', False), _connector='OR'), name='operacionsync_objeto_id_si_aplicada'),
        ),
    ]
