# Generated by Django 6.1.1 on 2026-09-20 17:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0008_movimientoinventario_venta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('cliente_nombre', models.CharField(max_length=150)),
                ('cliente_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.TextField()),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_entrega_estimada', models.DateField()),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_PROCESO', 'En Proceso'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado')], default='RECIBIDO', max_length=10)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utilidad_neta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CostoOperativoOrden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('concepto', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos', to='servicios.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoOrden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APLICADO', 'Aplicado')], default='PENDIENTE', max_length=10)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventario.producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='servicios.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medio_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('QR', 'Qr')], max_length=20)),
                ('estado_pago', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('PENDIENTE_VERIFICACION', 'Pendiente Verificacion')], default='CONFIRMADO', max_length=30)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos', to='servicios.ordentrabajo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ordentrabajo',
            constraint=models.CheckConstraint(condition=models.Q(('costo_total__gte', 0)), name='orden_costo_total_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='costooperativoorden',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='costooperativoorden_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='consumoorden',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='consumoorden_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='abono',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='abono_valor_positivo'),
        ),
    ]
