# Generated by Django 6.1.1 on 2026-09-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='estado_pago',
            field=models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('PENDIENTE_VERIFICACION', 'Pendiente Verificacion'), ('ANULADO', 'Anulado')], default='CONFIRMADO', max_length=30),
        ),
    ]
