# Generated by Django 6.1.1 on 2026-10-06 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_abono_estado_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='cancelada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_PROCESO', 'En Proceso'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado'), ('CANCELADA', 'Cancelada')], default='RECIBIDO', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='ordentrabajo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'CANCELADA'), _negated=True), models.Q(('motivo_cancelacion__isnull', False), ('cancelada_por__isnull', False), ('fecha_cancelacion__isnull', False)), _connector='OR'), name='orden_datos_cancelacion_si_cancelada'),
        ),
    ]
